import { Clock3, Facebook, Heart, Instagram, MapPin, Navigation, Phone, ShoppingBasket, Sparkles, Star } from 'lucide-react'
import { Header } from '../components/Header'
import { MobileActions } from '../components/MobileActions'
import { MotionReveal } from '../components/MotionReveal'
import { SectionHeading } from '../components/SectionHeading'
import { departments, gallery, reviews, store } from '../data/store'
import { useStoreStatus } from '../hooks/useStoreStatus'

export default function HomePage() {
  const status = useStoreStatus()
  return <><Header /><main id="top">
    <section className="hero"><div className="hero-image" role="img" aria-label="Beautiful fresh produce at a neighbourhood market" /><div className="hero-overlay" /><div className="shell hero-content">
      <MotionReveal><div className="status-pill"><span className={status.open ? 'status-dot' : 'status-dot closed'} />{status.label}</div><p className="hero-kicker">Windsor's neighbourhood market</p><h1>Fresh. Local.<br /><em>Convenient.</em></h1><p className="hero-sub">Fresh Produce <span>•</span> Beer & Wine <span>•</span> Italian Foods</p><p className="hero-copy">Everything you need for tonight's table—close to home and served with a neighbourly smile.</p><div className="hero-actions"><a className="button" href={store.phoneHref}><Phone size={20} /> Call Now</a><a className="button button-light" href={store.directionsUrl} target="_blank" rel="noreferrer"><Navigation size={20} /> Get Directions</a></div></MotionReveal>
    </div></section>

    <section className="trust-strip"><div className="shell trust-grid"><div><MapPin />Right in your neighbourhood</div><div><Clock3 />Open 7 days a week</div><div><ShoppingBasket />Fresh favourites in one stop</div></div></section>

    <section id="departments" className="section"><div className="shell"><SectionHeading eyebrow="Shop today" title="Something fresh for every table" body="Skip the long trip. Find dinner inspiration, everyday essentials, and Italian favourites right here in Windsor." />
      <div className="department-grid">{departments.map((item, index) => <MotionReveal key={item.title} className={index === 0 ? 'department-card featured' : 'department-card'}><img src={item.image} alt={item.alt} loading={index ? 'lazy' : 'eager'} /><div className="card-shade" /><div className="card-content"><span>0{index + 1}</span><h3>{item.title}</h3><p>{item.text}</p><a href="#visit">Visit us today <span aria-hidden="true">→</span></a></div></MotionReveal>)}</div>
    </div></section>

    <section id="about" className="section about-section"><div className="shell about-grid"><MotionReveal className="about-image-wrap"><img src="https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=85" alt="Friendly local grocery shopping experience" loading="lazy" /><div className="local-badge"><strong>Local</strong><span>Windsor, Ontario</span></div></MotionReveal><MotionReveal className="about-copy"><SectionHeading eyebrow="Your local market" title="Good food. Close to home." /><p>DeMarco's Fine Foods is the convenient neighbourhood stop for families, food lovers, and anyone who values fresh choices without the big-box experience.</p><p>Come in for the ingredients you need tonight, discover something delicious, and enjoy the friendly service that makes local shopping better.</p><a className="text-link" href={store.directionsUrl} target="_blank" rel="noreferrer">Find us on Grand Marais Road <Navigation size={18} /></a></MotionReveal></div></section>

    <section className="section why-section"><div className="shell"><SectionHeading eyebrow="Why DeMarco's" title="The better way to shop nearby" centered /><div className="why-grid">{[[Sparkles,'Fresh choices','Quality produce and foods selected for everyday meals.'],[Heart,'Neighbourly service','A welcoming local store where shopping feels personal.'],[ShoppingBasket,'Easy and convenient','Produce, Italian foods, beer and wine in one quick stop.']].map(([Icon,title,text]) => { const C = Icon as typeof Sparkles; return <MotionReveal className="why-card" key={title as string}><span><C /></span><h3>{title as string}</h3><p>{text as string}</p></MotionReveal>})}</div></div></section>

    <section id="reviews" className="section reviews-section"><div className="shell"><SectionHeading eyebrow="Loved locally" title="Why Windsor shops DeMarco's" body="A neighbourhood favourite for fresh food, convenience, and friendly service." /><div className="review-grid">{reviews.map((review) => <MotionReveal className="review-card" key={review.quote}><div className="stars" aria-label="5 stars">{[1,2,3,4,5].map(i => <Star key={i} size={18} fill="currentColor" />)}</div><blockquote>“{review.quote}”</blockquote><p>{review.name}</p></MotionReveal>)}</div><p className="review-note">Sample testimonials — replace with verified Google reviews before launch.</p></div></section>

    <section className="section gallery-section"><div className="shell"><SectionHeading eyebrow="In store" title="Fresh finds are waiting" body="Stop by today and see what catches your eye." /><div className="gallery-grid">{gallery.map(([src, alt], index) => <MotionReveal className={`gallery-item gallery-${index + 1}`} key={src}><img src={src} alt={alt} loading="lazy" /></MotionReveal>)}</div></div></section>

    <section id="visit" className="section visit-section"><div className="shell"><div className="visit-card"><div className="visit-details"><p className="eyebrow">Visit today</p><h2>Your neighbourhood market is just around the corner.</h2><div className="visit-list"><a href={store.directionsUrl} target="_blank" rel="noreferrer"><MapPin /><span><small>Address</small>{store.address}</span></a><a href={store.phoneHref}><Phone /><span><small>Phone</small>{store.phoneDisplay}</span></a><div><Clock3 /><span><small>Hours</small>Mon–Sat: 10 AM–8 PM<br />Sunday: 11 AM–4 PM</span></div></div><div className="visit-actions"><a className="button" href={store.directionsUrl} target="_blank" rel="noreferrer"><Navigation size={19} /> Get Directions</a><a className="social" href={store.instagram} target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram /></a><a className="social" href={store.facebook} target="_blank" rel="noreferrer" aria-label="Facebook"><Facebook /></a></div></div><div className="map-wrap"><iframe title="Map to DeMarco's Fine Foods" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=DeMarco%27s+Fine+Foods,+1349+Grand+Marais+Rd+W,+Windsor,+ON&output=embed" /></div></div></div></section>
  </main><footer><div className="shell footer-grid"><div><a href="#top" className="brand footer-brand"><span className="brand-mark">D</span><span>DeMarco's<small>Fine Foods</small></span></a><p>Fresh food and friendly service, right in your Windsor neighbourhood.</p></div><div><h3>Visit</h3><a href={store.directionsUrl} target="_blank" rel="noreferrer">1349 Grand Marais Rd W<br />Windsor, ON N9E 1E2</a><a href={store.phoneHref}>{store.phoneDisplay}</a></div><div><h3>Hours</h3><p>Monday–Saturday<br />10 AM–8 PM</p><p>Sunday<br />11 AM–4 PM</p></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} DeMarco's Fine Foods</span><span>Proudly serving Windsor, Ontario</span></div></footer><MobileActions /></>
}
